baseURL = "http://example.org/"
languageCode = "zh-Hans"
title = "凯的笔记"

theme = "book"

[params]
  BookRepo = "https://github.com/kaizhang91/notes"
  BookSection = "*"
  BookMenuBundle = "/menu"
  BookDateFormat = "2006-01-02"
