baseURL = "https://kaizhang91.github.io/notes/"
languageCode = "zh-Hans"
title = "凯的笔记"

theme = "book"
enableGitInfo = true

[params]
  BookRepo = "https://github.com/kaizhang91/notes"
  BookSection = "*"
  BookMenuBundle = "/menu"
  BookDateFormat = "2006-01-02 15:04:05 -0700"
